In [4]:
#import libraries
from bs4 import BeautifulSoup
import requests
import time
import datetime

import smtplib

In [88]:
#connect to website
URL = 'https://www.amazon.com/Sidefeel-Womens-Jeans-Waisted-Strechy/dp/B0D4QCQ9CQ/ref=sr_1_1?_encoding=UTF8&content-id=amzn1.sym.1cb3993a-41fc-4a2a-b2ee-016e70298d9f&crid=1TZCO6ZC2HZVA&dib=eyJ2IjoiMSJ9.Jz1wkl_9ebXMQcJOHxadnYm1XMr1Qo8LRYvrWhmkbt9fs2Vi_Uq0lstFgCO6mmmEM8h4nv2VCzLoskTdGWOTp1A7E30tXpjG-6jWNS9K8a-PJ7Du6ocHwoNJ396uUCWfV1jBUqefN5ner5rHca1Uwr6MhfJ09TD80QDQkeyL4jA_DvnrMksD5BoEbDC8wCI40kwVXpDbZ0EXqLk4FlTfKLOxNgnhPzLoHx4ucXXyJiROv1roEW3TBKpC8r8h16p9qROxUiHnVeAV-yXXn41PZc9Om6wz4rJDKBv-2rFibs8.1sa1UXR8e2__ezANH02pi9oEWVmF5YCd95lpx7L5-pQ&dib_tag=se&keywords=Jeans&pd_rd_r=f0047320-f5a1-4c59-a106-eb35861febf4&pd_rd_w=bC8Bk&pd_rd_wg=ubAiu&qid=1771696257&refinements=p_36%3A-5000&rnid=2941120011&s=apparel&sprefix=jeans%2Caps%2C155&sr=1-1&th=1&language=en_US&currency=USD&psc=1'
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

page = requests.get(URL, headers=headers)

soup1 = BeautifulSoup(page.content, "html.parser")

soup2 = BeautifulSoup(soup1.prettify(), 'html.parser')

title = soup2.find(id='productTitle').get_text()

price = soup2.find(id='apex-pricetopay-accessibility-label').get_text()

print(price)
print(title)

                 PHP 1,912.10


                 Sidefeel Women's Wide Leg Jeans High Waisted Stretchy Raw Hem Zimbaplatinum Denim Pants

In [90]:
price = price.strip()[4:]
title = title.strip()

print(price)
type(price)

1,912.10

str

In [104]:
import datetime
today = datetime.date.today()
print(today)

2026-02-22

In [108]:
#create csv

import csv

header = ['Product', 'Price', 'Date']
data = [title, price, today]


#with open('amazonwebscraper.csv', 'w', newline='', encoding='UTF8') as f:
 #   writer = csv.writer(f)
  #  writer.writerow(header)
  #  writer.writerow(data)

In [116]:
import pandas as pd
pd.read_csv(r'C:\Users\April\amazonwebscraper.csv')

                                             Product     Price        Date
0  Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
1  Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
2  Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22

In [114]:
#append data, change 'w' to 'a+'
with open('amazonwebscraper.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [150]:
def check_price():
    URL = 'https://www.amazon.com/Sidefeel-Womens-Jeans-Waisted-Strechy/dp/B0D4QCQ9CQ/ref=sr_1_1?_encoding=UTF8&content-id=amzn1.sym.1cb3993a-41fc-4a2a-b2ee-016e70298d9f&crid=1TZCO6ZC2HZVA&dib=eyJ2IjoiMSJ9.Jz1wkl_9ebXMQcJOHxadnYm1XMr1Qo8LRYvrWhmkbt9fs2Vi_Uq0lstFgCO6mmmEM8h4nv2VCzLoskTdGWOTp1A7E30tXpjG-6jWNS9K8a-PJ7Du6ocHwoNJ396uUCWfV1jBUqefN5ner5rHca1Uwr6MhfJ09TD80QDQkeyL4jA_DvnrMksD5BoEbDC8wCI40kwVXpDbZ0EXqLk4FlTfKLOxNgnhPzLoHx4ucXXyJiROv1roEW3TBKpC8r8h16p9qROxUiHnVeAV-yXXn41PZc9Om6wz4rJDKBv-2rFibs8.1sa1UXR8e2__ezANH02pi9oEWVmF5YCd95lpx7L5-pQ&dib_tag=se&keywords=Jeans&pd_rd_r=f0047320-f5a1-4c59-a106-eb35861febf4&pd_rd_w=bC8Bk&pd_rd_wg=ubAiu&qid=1771696257&refinements=p_36%3A-5000&rnid=2941120011&s=apparel&sprefix=jeans%2Caps%2C155&sr=1-1&th=1&language=en_US&currency=USD&psc=1'
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    page = requests.get(URL, headers=headers)

    soup1 = BeautifulSoup(page.content, "html.parser")

    soup2 = BeautifulSoup(soup1.prettify(), 'html.parser')

    title = soup2.find(id='productTitle').get_text()

    price = soup2.find(id='apex-pricetopay-accessibility-label').get_text()
    
    price = price.strip()[4:]
    title = title.strip()

    import datetime
    today = datetime.date.today()

    import csv

    header = ['Product', 'Price', 'Date']
    data = [title, price, today]

    with open('amazonwebscraper.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

    #convert price to int
    price_cnv = int(float(price.replace(',', '')))
    if((price_cnv) < 1900):
        send_mail()

In [ ]:
while(True):
    check_price()
    time.sleep(86400)

In [124]:
import pandas as pd
pd.read_csv(r'C:\Users\April\amazonwebscraper.csv')

                                              Product     Price        Date
0   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
1   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
2   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
3   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
4   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
5   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
6   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
7   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
8   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
9   Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22
10  Sidefeel Women's Wide Leg Jeans High Waisted S...  1,912.10  2026-02-22

In [ ]:
# send email when a price hits below a certain level

def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    #server.starttls()
    server.ehlo()
    server.login('apriltanjay@gmail.com','xxxxxxxxxxxxxx')
    
    subject = "The Shirt you want is below PHP 1900! Now is your chance to buy!"
    body = "April, This is the moment we have been waiting for. Now is your chance to pick up the pants of your dreams. Don't mess it up! Link here: https://www.amazon.com/Sidefeel-Womens-Jeans-Waisted-Strechy/dp/B0D4QCQ9CQ/ref=sr_1_1?_encoding=UTF8&content-id=amzn1.sym.1cb3993a-41fc-4a2a-b2ee-016e70298d9f&crid=1TZCO6ZC2HZVA&dib=eyJ2IjoiMSJ9.Jz1wkl_9ebXMQcJOHxadnYm1XMr1Qo8LRYvrWhmkbt9fs2Vi_Uq0lstFgCO6mmmEM8h4nv2VCzLoskTdGWOTp1A7E30tXpjG-6jWNS9K8a-PJ7Du6ocHwoNJ396uUCWfV1jBUqefN5ner5rHca1Uwr6MhfJ09TD80QDQkeyL4jA_DvnrMksD5BoEbDC8wCI40kwVXpDbZ0EXqLk4FlTfKLOxNgnhPzLoHx4ucXXyJiROv1roEW3TBKpC8r8h16p9qROxUiHnVeAV-yXXn41PZc9Om6wz4rJDKBv-2rFibs8.1sa1UXR8e2__ezANH02pi9oEWVmF5YCd95lpx7L5-pQ&dib_tag=se&keywords=Jeans&pd_rd_r=f0047320-f5a1-4c59-a106-eb35861febf4&pd_rd_w=bC8Bk&pd_rd_wg=ubAiu&qid=1771696257&refinements=p_36%3A-5000&rnid=2941120011&s=apparel&sprefix=jeans%2Caps%2C155&sr=1-1&th=1&language=en_US&currency=USD&psc=1"
   
    msg = f"Subject: {subject}\n\n{body}"
    
    server.sendmail(
        'apriltanjay@gmail.com',
        msg
    )